#include <string.h>
#include <Zydis/Zydis.h>
#include <Zydis/Internal/SharedData.h>
#include <Zydis/Internal/EncoderData.h>

#include "xstate.h"
#include "config.h" // A bit circular here, but needed to keep the strings in one place
#include "debug_strings.h"

const char *fuzz_method_strings[] = {
    [FUZZ_GENERATIVE]   = "Generative Fuzzing",
    [FUZZ_MUTATIVE]     = "Mutative Fuzzing",
    [FUZZ_HYBRID]       = "Hybrid Fuzzing"
};

const char *encode_method_strings[] = {
    [NORM_64_BYTE] = "Normalize every 8 bytes",
    [NORM_32_BYTE] = "Normalize every 4 bytes",
    [NORM_16_BYTE] = "Normalize every 2 bytes",
    [NORM_8_BYTE] = "Normalize every 1 bytes",
    [NORM_DIRECT]   = "Normalize every register"
};

const char *xfeature_strings[] = {
    [XFEATURE_FP] = "XFEATURE_FP",
    [XFEATURE_SSE] = "XFEATURE_SSE",
    [XFEATURE_YMM] = "XFEATURE_YMM",
    [XFEATURE_BNDREGS] = "XFEATURE_BNDREGS",
    [XFEATURE_BNDCSR] = "XFEATURE_BNDCSR",
    [XFEATURE_OPMASK] = "XFEATURE_OPMASK",
    [XFEATURE_ZMM_Hi256] = "XFEATURE_ZMM_Hi256",
    [XFEATURE_Hi16_ZMM] = "XFEATURE_Hi16_ZMM",
    [XFEATURE_PT_UNIMPLEMENTED_SO_FAR] = "XFEATURE_PT_UNIMPLEMENTED_SO_FAR",
    [XFEATURE_PKRU] = "XFEATURE_PKRU",
    [XFEATURE_PASID] = "XFEATURE_PASID",
    [XFEATURE_CET_USER] = "XFEATURE_CET_USER",
    [XFEATURE_CET_KERNEL] = "XFEATURE_CET_KERNEL",
    [XFEATURE_RSRVD_COMP_13] = "XFEATURE_RSRVD_COMP_13",
    [XFEATURE_RSRVD_COMP_14] = "XFEATURE_RSRVD_COMP_14",
    [XFEATURE_LBR] = "XFEATURE_LBR",
    [XFEATURE_RSRVD_COMP_16] = "XFEATURE_RSRVD_COMP_16",
    [XFEATURE_XTILE_CFG] = "XFEATURE_XTILE_CFG",
    [XFEATURE_XTILE_DATA] = "XFEATURE_XTILE_DATA",
    [XFEATURE_APX] = "XFEATURE_APX",
};

const char *zydis_machine_mode_strings[] = {
    [ZYDIS_MACHINE_MODE_LEGACY_16] = "ZYDIS_MACHINE_MODE_LEGACY_16",
    [ZYDIS_MACHINE_MODE_LEGACY_32] = "ZYDIS_MACHINE_MODE_LEGACY_32",
    [ZYDIS_MACHINE_MODE_LONG_64] = "ZYDIS_MACHINE_MODE_LONG_64",
    [ZYDIS_MACHINE_MODE_LONG_COMPAT_16] = "ZYDIS_MACHINE_MODE_LONG_COMPAT_16",
    [ZYDIS_MACHINE_MODE_LONG_COMPAT_32] = "ZYDIS_MACHINE_MODE_LONG_COMPAT_32",
    [ZYDIS_MACHINE_MODE_REAL_16] = "ZYDIS_MACHINE_MODE_REAL_16",
};

const char *zydis_vector_length_strings[] = {
    [ZYDIS_VECTOR_LENGTH_INVALID] = "ZYDIS_VECTOR_LENGTH_INVALID",
    [ZYDIS_VECTOR_LENGTH_128] = "ZYDIS_VECTOR_LENGTH_128",
    [ZYDIS_VECTOR_LENGTH_256] = "ZYDIS_VECTOR_LENGTH_256",
    [ZYDIS_VECTOR_LENGTH_512] = "ZYDIS_VECTOR_LENGTH_512",
};

const char *zydis_implreg_type_strings[] =  {
    [ZYDIS_IMPLREG_TYPE_STATIC] = "ZYDIS_IMPLREG_TYPE_STATIC",
    [ZYDIS_IMPLREG_TYPE_GPR_OSZ] = "ZYDIS_IMPLREG_TYPE_GPR_OSZ",
    [ZYDIS_IMPLREG_TYPE_GPR_ASZ] = "ZYDIS_IMPLREG_TYPE_GPR_ASZ",
    [ZYDIS_IMPLREG_TYPE_IP_ASZ] = "ZYDIS_IMPLREG_TYPE_IP_ASZ",
    [ZYDIS_IMPLREG_TYPE_IP_SSZ] = "ZYDIS_IMPLREG_TYPE_IP_SSZ",
    [ZYDIS_IMPLREG_TYPE_GPR_SSZ]  = "ZYDIS_IMPLREG_TYPE_GPR_SSZ",
    [ZYDIS_IMPLREG_TYPE_FLAGS_SSZ] = "ZYDIS_IMPLREG_TYPE_FLAGS_SSZ",
};

const char *zydis_implmem_type_strings[] = {
    [ZYDIS_IMPLMEM_BASE_AGPR_REG] = "ZYDIS_IMPLMEM_BASE_AGPR_REG",
    [ZYDIS_IMPLMEM_BASE_AGPR_RM] = "ZYDIS_IMPLMEM_BASE_AGPR_RM",
    [ZYDIS_IMPLMEM_BASE_AAX] = "ZYDIS_IMPLMEM_BASE_AAX",
    [ZYDIS_IMPLMEM_BASE_ADX] = "ZYDIS_IMPLMEM_BASE_ADX",
    [ZYDIS_IMPLMEM_BASE_ABX] = "ZYDIS_IMPLMEM_BASE_ABX",
    [ZYDIS_IMPLMEM_BASE_ASI] = "ZYDIS_IMPLMEM_BASE_ASI",
    [ZYDIS_IMPLMEM_BASE_ADI] = "ZYDIS_IMPLMEM_BASE_ADI",
    [ZYDIS_IMPLMEM_BASE_SSP] = "ZYDIS_IMPLMEM_BASE_SSP",
    [ZYDIS_IMPLMEM_BASE_SBP] = "ZYDIS_IMPLMEM_BASE_SBP",
};

// TODO: These will have to be expanded (automatically generate)
const char *zydis_mnemonic_strings[] = {
    [ZYDIS_MNEMONIC_XOR] = "XOR",
    [ZYDIS_MNEMONIC_SUB] = "SUB",
    [ZYDIS_MNEMONIC_ADD] = "ADD",
    [ZYDIS_MNEMONIC_CMP] = "CMP",
    [ZYDIS_MNEMONIC_MOV] = "MOV",
    [ZYDIS_MNEMONIC_JMP] = "JMP",
    [ZYDIS_MNEMONIC_JNZ] = "JNZ",
    [ZYDIS_MNEMONIC_JZ] = "JZ",
    [ZYDIS_MNEMONIC_RET] = "RET",
    [ZYDIS_MNEMONIC_NOT] = "NOT",
    [ZYDIS_MNEMONIC_TEST] = "TEST",

    // These are essentially null op instructions
    [ZYDIS_MNEMONIC_NOP] = "NOP",
    [ZYDIS_MNEMONIC_LFENCE] = "LFENCE",
    [ZYDIS_MNEMONIC_MFENCE] = "MFENCE",
    [ZYDIS_MNEMONIC_SFENCE] = "SFENCE",
};

const char *zydis_operand_type_strings[] = {
    [ZYDIS_OPERAND_TYPE_UNUSED] = "UNUSED",
    [ZYDIS_OPERAND_TYPE_IMMEDIATE] = "IMM",
    [ZYDIS_OPERAND_TYPE_POINTER] = "PTR",
    [ZYDIS_OPERAND_TYPE_REGISTER] = "REG",
    [ZYDIS_OPERAND_TYPE_MEMORY] = "MEM",
};

const char *zydis_operand_action_strings[] = {
    [ZYDIS_OPERAND_ACTION_CONDREAD] = "ZYDIS_OPERAND_ACTION_CONDREAD",
    [ZYDIS_OPERAND_ACTION_CONDREAD_CONDWRITE] = "ZYDIS_OPERAND_ACTION_CONDREAD_CONDWRITE",
    [ZYDIS_OPERAND_ACTION_CONDREAD_WRITE] = "ZYDIS_OPERAND_ACTION_CONDREAD_WRITE",
    [ZYDIS_OPERAND_ACTION_CONDWRITE] = "ZYDIS_OPERAND_ACTION_CONDWRITE",
    [ZYDIS_OPERAND_ACTION_MASK_READ] = "ZYDIS_OPERAND_ACTION_MASK_READ",
    [ZYDIS_OPERAND_ACTION_MASK_WRITE] = "ZYDIS_OPERAND_ACTION_MASK_WRITE",
    [ZYDIS_OPERAND_ACTION_READ] = "ZYDIS_OPERAND_ACTION_READ",
    [ZYDIS_OPERAND_ACTION_READWRITE] = "ZYDIS_OPERAND_ACTION_READWRITE",
    [ZYDIS_OPERAND_ACTION_READ_CONDWRITE] = "ZYDIS_OPERAND_ACTION_READ_CONDWRITE",
    [ZYDIS_OPERAND_ACTION_WRITE] = "ZYDIS_OPERAND_ACTION_WRITE",
};

const char *zydis_operand_visibility_strings[] = {
    [ZYDIS_OPERAND_VISIBILITY_EXPLICIT] = "ZYDIS_OPERAND_VISIBILITY_EXPLICIT",
    [ZYDIS_OPERAND_VISIBILITY_HIDDEN] = "ZYDIS_OPERAND_VISIBILITY_HIDDEN",
    [ZYDIS_OPERAND_VISIBILITY_IMPLICIT] = "ZYDIS_OPERAND_VISIBILITY_IMPLICIT",
    [ZYDIS_OPERAND_VISIBILITY_INVALID] = "ZYDIS_OPERAND_VISIBILITY_INVALID",
};

const char *zydis_semantic_optype_strings[] = {
    [ZYDIS_SEMANTIC_OPTYPE_AGEN] = "ZYDIS_SEMANTIC_OPTYPE_AGEN",
    [ZYDIS_SEMANTIC_OPTYPE_BND] = "ZYDIS_SEMANTIC_OPTYPE_BND",
    [ZYDIS_SEMANTIC_OPTYPE_CR] = "ZYDIS_SEMANTIC_OPTYPE_CR",
    [ZYDIS_SEMANTIC_OPTYPE_DR] = "ZYDIS_SEMANTIC_OPTYPE_DR",
    [ZYDIS_SEMANTIC_OPTYPE_FPR] = "ZYDIS_SEMANTIC_OPTYPE_FPR",
    [ZYDIS_SEMANTIC_OPTYPE_GPR16] = "ZYDIS_SEMANTIC_OPTYPE_GPR16",
    [ZYDIS_SEMANTIC_OPTYPE_GPR16_32_32] = "ZYDIS_SEMANTIC_OPTYPE_GPR16_32_32",
    [ZYDIS_SEMANTIC_OPTYPE_GPR16_32_64] = "ZYDIS_SEMANTIC_OPTYPE_GPR16_32_64",
    [ZYDIS_SEMANTIC_OPTYPE_GPR32] = "ZYDIS_SEMANTIC_OPTYPE_GPR32",
    [ZYDIS_SEMANTIC_OPTYPE_GPR32_32_64] = "ZYDIS_SEMANTIC_OPTYPE_GPR32_32_64",
    [ZYDIS_SEMANTIC_OPTYPE_GPR64] = "ZYDIS_SEMANTIC_OPTYPE_GPR64",
    [ZYDIS_SEMANTIC_OPTYPE_GPR8] = "ZYDIS_SEMANTIC_OPTYPE_GPR8",
    [ZYDIS_SEMANTIC_OPTYPE_GPR_ASZ] = "ZYDIS_SEMANTIC_OPTYPE_GPR_ASZ",
    [ZYDIS_SEMANTIC_OPTYPE_IMM] = "ZYDIS_SEMANTIC_OPTYPE_IMM",
    [ZYDIS_SEMANTIC_OPTYPE_IMPLICIT_IMM1] = "ZYDIS_SEMANTIC_OPTYPE_IMPLICIT_IMM1",
    [ZYDIS_SEMANTIC_OPTYPE_IMPLICIT_MEM] = "ZYDIS_SEMANTIC_OPTYPE_IMPLICIT_MEM",
    [ZYDIS_SEMANTIC_OPTYPE_IMPLICIT_REG] = "ZYDIS_SEMANTIC_OPTYPE_IMPLICIT_REG",
    [ZYDIS_SEMANTIC_OPTYPE_MASK] = "ZYDIS_SEMANTIC_OPTYPE_MASK",
    [ZYDIS_SEMANTIC_OPTYPE_MEM] = "ZYDIS_SEMANTIC_OPTYPE_MEM",
    [ZYDIS_SEMANTIC_OPTYPE_MEM_VSIBX] = "ZYDIS_SEMANTIC_OPTYPE_MEM_VSIBX",
    [ZYDIS_SEMANTIC_OPTYPE_MEM_VSIBY] = "ZYDIS_SEMANTIC_OPTYPE_MEM_VSIBY",
    [ZYDIS_SEMANTIC_OPTYPE_MEM_VSIBZ] = "ZYDIS_SEMANTIC_OPTYPE_MEM_VSIBZ",
    [ZYDIS_SEMANTIC_OPTYPE_MIB] = "ZYDIS_SEMANTIC_OPTYPE_MIB",
    [ZYDIS_SEMANTIC_OPTYPE_MMX] = "ZYDIS_SEMANTIC_OPTYPE_MMX",
    [ZYDIS_SEMANTIC_OPTYPE_MOFFS] = "ZYDIS_SEMANTIC_OPTYPE_MOFFS",
    [ZYDIS_SEMANTIC_OPTYPE_PTR] = "ZYDIS_SEMANTIC_OPTYPE_PTR",
    [ZYDIS_SEMANTIC_OPTYPE_REL] = "ZYDIS_SEMANTIC_OPTYPE_REL",
    [ZYDIS_SEMANTIC_OPTYPE_SREG] = "ZYDIS_SEMANTIC_OPTYPE_SREG",
    [ZYDIS_SEMANTIC_OPTYPE_TMM] = "ZYDIS_SEMANTIC_OPTYPE_TMM",
    [ZYDIS_SEMANTIC_OPTYPE_UNUSED] = "ZYDIS_SEMANTIC_OPTYPE_UNUSED",
    [ZYDIS_SEMANTIC_OPTYPE_XMM] = "ZYDIS_SEMANTIC_OPTYPE_XMM",
    [ZYDIS_SEMANTIC_OPTYPE_YMM] = "ZYDIS_SEMANTIC_OPTYPE_YMM",
    [ZYDIS_SEMANTIC_OPTYPE_ZMM] = "ZYDIS_SEMANTIC_OPTYPE_ZMM"
};

const char *zydis_category_strings[] = {
    [ZYDIS_CATEGORY_ADOX_ADCX] = "ZYDIS_CATEGORY_ADOX_ADCX",
    [ZYDIS_CATEGORY_AES] = "ZYDIS_CATEGORY_AES",
    [ZYDIS_CATEGORY_AMD3DNOW] = "ZYDIS_CATEGORY_AMD3DNOW",
    [ZYDIS_CATEGORY_AMX_TILE] = "ZYDIS_CATEGORY_AMX_TILE",
    [ZYDIS_CATEGORY_AVX] = "ZYDIS_CATEGORY_AVX",
    [ZYDIS_CATEGORY_AVX2] = "ZYDIS_CATEGORY_AVX2",
    [ZYDIS_CATEGORY_AVX2GATHER] = "ZYDIS_CATEGORY_AVX2GATHER",
    [ZYDIS_CATEGORY_AVX512] = "ZYDIS_CATEGORY_AVX512",
    [ZYDIS_CATEGORY_AVX512_4FMAPS] = "ZYDIS_CATEGORY_AVX512_4FMAPS",
    [ZYDIS_CATEGORY_AVX512_4VNNIW] = "ZYDIS_CATEGORY_AVX512_4VNNIW",
    [ZYDIS_CATEGORY_AVX512_BITALG] = "ZYDIS_CATEGORY_AVX512_BITALG",
    [ZYDIS_CATEGORY_AVX512_VBMI] = "ZYDIS_CATEGORY_AVX512_VBMI",
    [ZYDIS_CATEGORY_AVX512_VP2INTERSECT] = "ZYDIS_CATEGORY_AVX512_VP2INTERSECT",
    [ZYDIS_CATEGORY_AVX_IFMA] = "ZYDIS_CATEGORY_AVX_IFMA",
    [ZYDIS_CATEGORY_BINARY] = "ZYDIS_CATEGORY_BINARY",
    [ZYDIS_CATEGORY_BITBYTE] = "ZYDIS_CATEGORY_BITBYTE",
    [ZYDIS_CATEGORY_BLEND] = "ZYDIS_CATEGORY_BLEND",
    [ZYDIS_CATEGORY_BMI1] = "ZYDIS_CATEGORY_BMI1",
    [ZYDIS_CATEGORY_BMI2] = "ZYDIS_CATEGORY_BMI2",
    [ZYDIS_CATEGORY_BROADCAST] = "ZYDIS_CATEGORY_BROADCAST",
    [ZYDIS_CATEGORY_CALL] = "ZYDIS_CATEGORY_CALL",
    [ZYDIS_CATEGORY_CET] = "ZYDIS_CATEGORY_CET",
    [ZYDIS_CATEGORY_CLDEMOTE] = "ZYDIS_CATEGORY_CLDEMOTE",
    [ZYDIS_CATEGORY_CLFLUSHOPT] = "ZYDIS_CATEGORY_CLFLUSHOPT",
    [ZYDIS_CATEGORY_CLWB] = "ZYDIS_CATEGORY_CLWB",
    [ZYDIS_CATEGORY_CLZERO] = "ZYDIS_CATEGORY_CLZERO",
    [ZYDIS_CATEGORY_CMOV] = "ZYDIS_CATEGORY_CMOV",
    [ZYDIS_CATEGORY_COMPRESS] = "ZYDIS_CATEGORY_COMPRESS",
    [ZYDIS_CATEGORY_COND_BR] = "ZYDIS_CATEGORY_COND_BR",
    [ZYDIS_CATEGORY_CONFLICT] = "ZYDIS_CATEGORY_CONFLICT",
    [ZYDIS_CATEGORY_CONVERT] = "ZYDIS_CATEGORY_CONVERT",
    [ZYDIS_CATEGORY_DATAXFER] = "ZYDIS_CATEGORY_DATAXFER",
    [ZYDIS_CATEGORY_DECIMAL] = "ZYDIS_CATEGORY_DECIMAL",
    [ZYDIS_CATEGORY_ENQCMD] = "ZYDIS_CATEGORY_ENQCMD",
    [ZYDIS_CATEGORY_EXPAND] = "ZYDIS_CATEGORY_EXPAND",
    [ZYDIS_CATEGORY_FCMOV] = "ZYDIS_CATEGORY_FCMOV",
    [ZYDIS_CATEGORY_FLAGOP] = "ZYDIS_CATEGORY_FLAGOP",
    [ZYDIS_CATEGORY_FMA4] = "ZYDIS_CATEGORY_FMA4",
    [ZYDIS_CATEGORY_FP16] = "ZYDIS_CATEGORY_FP16",
    [ZYDIS_CATEGORY_GATHER] = "ZYDIS_CATEGORY_GATHER",
    [ZYDIS_CATEGORY_GFNI] = "ZYDIS_CATEGORY_GFNI",
    [ZYDIS_CATEGORY_HRESET] = "ZYDIS_CATEGORY_HRESET",
    [ZYDIS_CATEGORY_IFMA] = "ZYDIS_CATEGORY_IFMA",
    [ZYDIS_CATEGORY_INTERRUPT] = "ZYDIS_CATEGORY_INTERRUPT",
    [ZYDIS_CATEGORY_INVALID] = "ZYDIS_CATEGORY_INVALID",
    [ZYDIS_CATEGORY_IO] = "ZYDIS_CATEGORY_IO",
    [ZYDIS_CATEGORY_IOSTRINGOP] = "ZYDIS_CATEGORY_IOSTRINGOP",
    [ZYDIS_CATEGORY_KEYLOCKER] = "ZYDIS_CATEGORY_KEYLOCKER",
    [ZYDIS_CATEGORY_KEYLOCKER_WIDE] = "ZYDIS_CATEGORY_KEYLOCKER_WIDE",
    [ZYDIS_CATEGORY_KMASK] = "ZYDIS_CATEGORY_KMASK",
    [ZYDIS_CATEGORY_KNC] = "ZYDIS_CATEGORY_KNC",
    [ZYDIS_CATEGORY_KNCMASK] = "ZYDIS_CATEGORY_KNCMASK",
    [ZYDIS_CATEGORY_KNCSCALAR] = "ZYDIS_CATEGORY_KNCSCALAR",
    [ZYDIS_CATEGORY_LEGACY] = "ZYDIS_CATEGORY_LEGACY",
    [ZYDIS_CATEGORY_LOGICAL] = "ZYDIS_CATEGORY_LOGICAL",
    [ZYDIS_CATEGORY_LOGICAL_FP] = "ZYDIS_CATEGORY_LOGICAL_FP",
    [ZYDIS_CATEGORY_LZCNT] = "ZYDIS_CATEGORY_LZCNT",
    [ZYDIS_CATEGORY_MISC] = "ZYDIS_CATEGORY_MISC",
    [ZYDIS_CATEGORY_MMX] = "ZYDIS_CATEGORY_MMX",
    [ZYDIS_CATEGORY_MOVDIR] = "ZYDIS_CATEGORY_MOVDIR",
    [ZYDIS_CATEGORY_MPX] = "ZYDIS_CATEGORY_MPX",
    [ZYDIS_CATEGORY_MSRLIST] = "ZYDIS_CATEGORY_MSRLIST",
    [ZYDIS_CATEGORY_NOP] = "ZYDIS_CATEGORY_NOP",
    [ZYDIS_CATEGORY_PADLOCK] = "ZYDIS_CATEGORY_PADLOCK",
    [ZYDIS_CATEGORY_PBNDKB] = "ZYDIS_CATEGORY_PBNDKB",
    [ZYDIS_CATEGORY_PCLMULQDQ] = "ZYDIS_CATEGORY_PCLMULQDQ",
    [ZYDIS_CATEGORY_PCOMMIT] = "ZYDIS_CATEGORY_PCOMMIT",
    [ZYDIS_CATEGORY_PCONFIG] = "ZYDIS_CATEGORY_PCONFIG",
    [ZYDIS_CATEGORY_PKU] = "ZYDIS_CATEGORY_PKU",
    [ZYDIS_CATEGORY_POP] = "ZYDIS_CATEGORY_POP",
    [ZYDIS_CATEGORY_PREFETCH] = "ZYDIS_CATEGORY_PREFETCH",
    [ZYDIS_CATEGORY_PREFETCHWT1] = "ZYDIS_CATEGORY_PREFETCHWT1",
    [ZYDIS_CATEGORY_PT] = "ZYDIS_CATEGORY_PT",
    [ZYDIS_CATEGORY_PUSH] = "ZYDIS_CATEGORY_PUSH",
    [ZYDIS_CATEGORY_RDPID] = "ZYDIS_CATEGORY_RDPID",
    [ZYDIS_CATEGORY_RDPRU] = "ZYDIS_CATEGORY_RDPRU",
    [ZYDIS_CATEGORY_RDRAND] = "ZYDIS_CATEGORY_RDRAND",
    [ZYDIS_CATEGORY_RDSEED] = "ZYDIS_CATEGORY_RDSEED",
    [ZYDIS_CATEGORY_RDWRFSGS] = "ZYDIS_CATEGORY_RDWRFSGS",
    [ZYDIS_CATEGORY_RET] = "ZYDIS_CATEGORY_RET",
    [ZYDIS_CATEGORY_ROTATE] = "ZYDIS_CATEGORY_ROTATE",
    [ZYDIS_CATEGORY_SCATTER] = "ZYDIS_CATEGORY_SCATTER",
    [ZYDIS_CATEGORY_SEGOP] = "ZYDIS_CATEGORY_SEGOP",
    [ZYDIS_CATEGORY_SEMAPHORE] = "ZYDIS_CATEGORY_SEMAPHORE",
    [ZYDIS_CATEGORY_SERIALIZE] = "ZYDIS_CATEGORY_SERIALIZE",
    [ZYDIS_CATEGORY_SETCC] = "ZYDIS_CATEGORY_SETCC",
    [ZYDIS_CATEGORY_SGX] = "ZYDIS_CATEGORY_SGX",
    [ZYDIS_CATEGORY_SHA] = "ZYDIS_CATEGORY_SHA",
    [ZYDIS_CATEGORY_SHA512] = "ZYDIS_CATEGORY_SHA512",
    [ZYDIS_CATEGORY_SHIFT] = "ZYDIS_CATEGORY_SHIFT",
    [ZYDIS_CATEGORY_SMAP] = "ZYDIS_CATEGORY_SMAP",
    [ZYDIS_CATEGORY_SSE] = "ZYDIS_CATEGORY_SSE",
    [ZYDIS_CATEGORY_STRINGOP] = "ZYDIS_CATEGORY_STRINGOP",
    [ZYDIS_CATEGORY_STTNI] = "ZYDIS_CATEGORY_STTNI",
    [ZYDIS_CATEGORY_SYSCALL] = "ZYDIS_CATEGORY_SYSCALL",
    [ZYDIS_CATEGORY_SYSRET] = "ZYDIS_CATEGORY_SYSRET",
    [ZYDIS_CATEGORY_SYSTEM] = "ZYDIS_CATEGORY_SYSTEM",
    [ZYDIS_CATEGORY_TBM] = "ZYDIS_CATEGORY_TBM",
    [ZYDIS_CATEGORY_TSX_LDTRK] = "ZYDIS_CATEGORY_TSX_LDTRK",
    [ZYDIS_CATEGORY_UFMA] = "ZYDIS_CATEGORY_UFMA",
    [ZYDIS_CATEGORY_UINTR] = "ZYDIS_CATEGORY_UINTR",
    [ZYDIS_CATEGORY_UNCOND_BR] = "ZYDIS_CATEGORY_UNCOND_BR",
    [ZYDIS_CATEGORY_VAES] = "ZYDIS_CATEGORY_VAES",
    [ZYDIS_CATEGORY_VBMI2] = "ZYDIS_CATEGORY_VBMI2",
    [ZYDIS_CATEGORY_VEX] = "ZYDIS_CATEGORY_VEX",
    [ZYDIS_CATEGORY_VFMA] = "ZYDIS_CATEGORY_VFMA",
    [ZYDIS_CATEGORY_VPCLMULQDQ] = "ZYDIS_CATEGORY_VPCLMULQDQ",
    [ZYDIS_CATEGORY_VTX] = "ZYDIS_CATEGORY_VTX",
    [ZYDIS_CATEGORY_WAITPKG] = "ZYDIS_CATEGORY_WAITPKG",
    [ZYDIS_CATEGORY_WIDENOP] = "ZYDIS_CATEGORY_WIDENOP",
    [ZYDIS_CATEGORY_WRMSRNS] = "ZYDIS_CATEGORY_WRMSRNS",
    [ZYDIS_CATEGORY_X87_ALU] = "ZYDIS_CATEGORY_X87_ALU",
    [ZYDIS_CATEGORY_XOP] = "ZYDIS_CATEGORY_XOP",
    [ZYDIS_CATEGORY_XSAVE] = "ZYDIS_CATEGORY_XSAVE",
    [ZYDIS_CATEGORY_XSAVEOPT] = "ZYDIS_CATEGORY_XSAVEOPT"
};

const char *zydis_ielement_type_strings[] = {
    [ZYDIS_IELEMENT_TYPE_BCD80] = "ZYDIS_IELEMENT_TYPE_BCD80",
    [ZYDIS_IELEMENT_TYPE_BFLOAT16X2] = "ZYDIS_IELEMENT_TYPE_BFLOAT16X2",
    [ZYDIS_IELEMENT_TYPE_CC3] = "ZYDIS_IELEMENT_TYPE_CC3",
    [ZYDIS_IELEMENT_TYPE_CC5] = "ZYDIS_IELEMENT_TYPE_CC5",
    [ZYDIS_IELEMENT_TYPE_FLOAT16] = "ZYDIS_IELEMENT_TYPE_FLOAT16",
    [ZYDIS_IELEMENT_TYPE_FLOAT16X2] = "ZYDIS_IELEMENT_TYPE_FLOAT16X2",
    [ZYDIS_IELEMENT_TYPE_FLOAT32] = "ZYDIS_IELEMENT_TYPE_FLOAT32",
    [ZYDIS_IELEMENT_TYPE_FLOAT64] = "ZYDIS_IELEMENT_TYPE_FLOAT64",
    [ZYDIS_IELEMENT_TYPE_FLOAT80] = "ZYDIS_IELEMENT_TYPE_FLOAT80",
    [ZYDIS_IELEMENT_TYPE_INT] = "ZYDIS_IELEMENT_TYPE_INT",
    [ZYDIS_IELEMENT_TYPE_INT1] = "ZYDIS_IELEMENT_TYPE_INT1",
    [ZYDIS_IELEMENT_TYPE_INT16] = "ZYDIS_IELEMENT_TYPE_INT16",
    [ZYDIS_IELEMENT_TYPE_INT16X2] = "ZYDIS_IELEMENT_TYPE_INT16X2",
    [ZYDIS_IELEMENT_TYPE_INT32] = "ZYDIS_IELEMENT_TYPE_INT32",
    [ZYDIS_IELEMENT_TYPE_INT64] = "ZYDIS_IELEMENT_TYPE_INT64",
    [ZYDIS_IELEMENT_TYPE_INT8] = "ZYDIS_IELEMENT_TYPE_INT8",
    [ZYDIS_IELEMENT_TYPE_INT8X4] = "ZYDIS_IELEMENT_TYPE_INT8X4",
    [ZYDIS_IELEMENT_TYPE_INVALID] = "ZYDIS_IELEMENT_TYPE_INVALID",
    [ZYDIS_IELEMENT_TYPE_STRUCT] = "ZYDIS_IELEMENT_TYPE_STRUCT",
    [ZYDIS_IELEMENT_TYPE_UINT] = "ZYDIS_IELEMENT_TYPE_UINT",
    [ZYDIS_IELEMENT_TYPE_UINT128] = "ZYDIS_IELEMENT_TYPE_UINT128",
    [ZYDIS_IELEMENT_TYPE_UINT16] = "ZYDIS_IELEMENT_TYPE_UINT16",
    [ZYDIS_IELEMENT_TYPE_UINT16X2] = "ZYDIS_IELEMENT_TYPE_UINT16X2",
    [ZYDIS_IELEMENT_TYPE_UINT256] = "ZYDIS_IELEMENT_TYPE_UINT256",
    [ZYDIS_IELEMENT_TYPE_UINT32] = "ZYDIS_IELEMENT_TYPE_UINT32",
    [ZYDIS_IELEMENT_TYPE_UINT64] = "ZYDIS_IELEMENT_TYPE_UINT64",
    [ZYDIS_IELEMENT_TYPE_UINT8] = "ZYDIS_IELEMENT_TYPE_UINT8",
    [ZYDIS_IELEMENT_TYPE_UINT8X4] = "ZYDIS_IELEMENT_TYPE_UINT8X4",
    [ZYDIS_IELEMENT_TYPE_VARIABLE] = "ZYDIS_IELEMENT_TYPE_VARIABLE"
};

const char *zydis_instruction_encoding_strings[] = {
    [ZYDIS_INSTRUCTION_ENCODING_3DNOW] = "ZYDIS_INSTRUCTION_ENCODING_3DNOW",
    [ZYDIS_INSTRUCTION_ENCODING_EVEX] = "ZYDIS_INSTRUCTION_ENCODING_EVEX",
    [ZYDIS_INSTRUCTION_ENCODING_LEGACY] = "ZYDIS_INSTRUCTION_ENCODING_LEGACY",
    [ZYDIS_INSTRUCTION_ENCODING_MVEX] = "ZYDIS_INSTRUCTION_ENCODING_MVEX",
    [ZYDIS_INSTRUCTION_ENCODING_VEX] = "ZYDIS_INSTRUCTION_ENCODING_VEX",
    [ZYDIS_INSTRUCTION_ENCODING_XOP] = "ZYDIS_INSTRUCTION_ENCODING_XOP"
};

const char *zydis_width_strings[] = {
    [ZYDIS_WIDTH_INVALID] = "ZYDIS_WIDTH_INVALID",
    [ZYDIS_WIDTH_16] = "ZYDIS_WIDTH_16",
    [ZYDIS_WIDTH_32] = "ZYDIS_WIDTH_32",
    [ZYDIS_WIDTH_64] = "ZYDIS_WIDTH_64"
};

const char *zydis_mandatory_prefix_strings[] = {
    [ZYDIS_MANDATORY_PREFIX_NONE] = "ZYDIS_MANDATORY_PREFIX_NONE",
    [ZYDIS_MANDATORY_PREFIX_66] = "ZYDIS_MANDATORY_PREFIX_66",
    [ZYDIS_MANDATORY_PREFIX_F2] = "ZYDIS_MANDATORY_PREFIX_F2",
    [ZYDIS_MANDATORY_PREFIX_F3] = "ZYDIS_MANDATORY_PREFIX_F3"
};

const char *zydis_branch_type_strings[] = {
    [ZYDIS_BRANCH_TYPE_FAR] = "ZYDIS_BRANCH_TYPE_FAR",
    [ZYDIS_BRANCH_TYPE_NEAR] = "ZYDIS_BRANCH_TYPE_NEAR",
    [ZYDIS_BRANCH_TYPE_NONE] = "ZYDIS_BRANCH_TYPE_NONE",
    [ZYDIS_BRANCH_TYPE_SHORT] = "ZYDIS_BRANCH_TYPE_SHORT"
};

const char *zydis_size_hint_strings[] = {
    [ZYDIS_SIZE_HINT_NONE] = "ZYDIS_SIZE_HINT_NONE",
    [ZYDIS_SIZE_HINT_ASZ] = "ZYDIS_SIZE_HINT_ASZ",
    [ZYDIS_SIZE_HINT_OSZ] = "ZYDIS_SIZE_HINT_OSZ"
};

const char *zydis_operand_encoding_strings[] = {
    [ZYDIS_OPERAND_ENCODING_DISP16] = "ZYDIS_OPERAND_ENCODING_DISP16",
    [ZYDIS_OPERAND_ENCODING_DISP16_32_32] = "ZYDIS_OPERAND_ENCODING_DISP16_32_32",
    [ZYDIS_OPERAND_ENCODING_DISP16_32_64] = "ZYDIS_OPERAND_ENCODING_DISP16_32_64",
    [ZYDIS_OPERAND_ENCODING_DISP32] = "ZYDIS_OPERAND_ENCODING_DISP32",
    [ZYDIS_OPERAND_ENCODING_DISP32_32_64] = "ZYDIS_OPERAND_ENCODING_DISP32_32_64",
    [ZYDIS_OPERAND_ENCODING_DISP64] = "ZYDIS_OPERAND_ENCODING_DISP64",
    [ZYDIS_OPERAND_ENCODING_DISP8] = "ZYDIS_OPERAND_ENCODING_DISP8",
    [ZYDIS_OPERAND_ENCODING_IS4] = "ZYDIS_OPERAND_ENCODING_IS4",
    [ZYDIS_OPERAND_ENCODING_JIMM16] = "ZYDIS_OPERAND_ENCODING_JIMM16",
    [ZYDIS_OPERAND_ENCODING_JIMM16_32_32] = "ZYDIS_OPERAND_ENCODING_JIMM16_32_32",
    [ZYDIS_OPERAND_ENCODING_JIMM16_32_64] = "ZYDIS_OPERAND_ENCODING_JIMM16_32_64",
    [ZYDIS_OPERAND_ENCODING_JIMM32] = "ZYDIS_OPERAND_ENCODING_JIMM32",
    [ZYDIS_OPERAND_ENCODING_JIMM32_32_64] = "ZYDIS_OPERAND_ENCODING_JIMM32_32_64",
    [ZYDIS_OPERAND_ENCODING_JIMM64] = "ZYDIS_OPERAND_ENCODING_JIMM64",
    [ZYDIS_OPERAND_ENCODING_JIMM8] = "ZYDIS_OPERAND_ENCODING_JIMM8",
    [ZYDIS_OPERAND_ENCODING_MASK] = "ZYDIS_OPERAND_ENCODING_MASK",
    [ZYDIS_OPERAND_ENCODING_MODRM_REG] = "ZYDIS_OPERAND_ENCODING_MODRM_REG",
    [ZYDIS_OPERAND_ENCODING_MODRM_RM] = "ZYDIS_OPERAND_ENCODING_MODRM_RM",
    [ZYDIS_OPERAND_ENCODING_NDSNDD] = "ZYDIS_OPERAND_ENCODING_NDSNDD",
    [ZYDIS_OPERAND_ENCODING_NONE] = "ZYDIS_OPERAND_ENCODING_NONE",
    [ZYDIS_OPERAND_ENCODING_OPCODE] = "ZYDIS_OPERAND_ENCODING_OPCODE",
    [ZYDIS_OPERAND_ENCODING_SIMM16] = "ZYDIS_OPERAND_ENCODING_SIMM16",
    [ZYDIS_OPERAND_ENCODING_SIMM16_32_32] = "ZYDIS_OPERAND_ENCODING_SIMM16_32_32",
    [ZYDIS_OPERAND_ENCODING_SIMM16_32_64] = "ZYDIS_OPERAND_ENCODING_SIMM16_32_64",
    [ZYDIS_OPERAND_ENCODING_SIMM32] = "ZYDIS_OPERAND_ENCODING_SIMM32",
    [ZYDIS_OPERAND_ENCODING_SIMM32_32_64] = "ZYDIS_OPERAND_ENCODING_SIMM32_32_64",
    [ZYDIS_OPERAND_ENCODING_SIMM64] = "ZYDIS_OPERAND_ENCODING_SIMM64",
    [ZYDIS_OPERAND_ENCODING_SIMM8] = "ZYDIS_OPERAND_ENCODING_SIMM8",
    [ZYDIS_OPERAND_ENCODING_UIMM16] = "ZYDIS_OPERAND_ENCODING_UIMM16",
    [ZYDIS_OPERAND_ENCODING_UIMM16_32_32] = "ZYDIS_OPERAND_ENCODING_UIMM16_32_32",
    [ZYDIS_OPERAND_ENCODING_UIMM16_32_64] = "ZYDIS_OPERAND_ENCODING_UIMM16_32_64",
    [ZYDIS_OPERAND_ENCODING_UIMM32] = "ZYDIS_OPERAND_ENCODING_UIMM32",
    [ZYDIS_OPERAND_ENCODING_UIMM32_32_64] = "ZYDIS_OPERAND_ENCODING_UIMM32_32_64",
    [ZYDIS_OPERAND_ENCODING_UIMM64] = "ZYDIS_OPERAND_ENCODING_UIMM64",
    [ZYDIS_OPERAND_ENCODING_UIMM8] = "ZYDIS_OPERAND_ENCODING_UIMM8"
};
